tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑"
    behind: "↓"
    staged: "+"
    conflict: "!"
    modified: "~"
    untracked: "?"
    stashed: "*"
    clean: "✓"
  styles:
    clear: "#[fg=#6c6f85]"
    state: "#[fg=#d20f39,bold]"
    branch: "#[fg=#7287fd,bold]"
    remote: "#[fg=#04a5e5]"
    staged: "#[fg=#40a02b]"
    conflict: "#[fg=#d20f39,bold]"
    modified: "#[fg=#fe640b]"
    untracked: "#[fg=#9ca0b0]"
    stashed: "#[fg=#179299]"
    clean: "#[fg=#40a02b]"
  layout: [branch, " ", flags]
  options:
    branch_max_len: 30
    hide_clean: false
